# Generated by Django 6.0.5 on 2026-05-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_rm_add_earned'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permission',
            name='unique_module_action',
        ),
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='unique_role_permission',
        ),
        migrations.RemoveConstraint(
            model_name='userbrand',
            name='unique_user_brand',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='amount_earned',
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('module', 'action')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='userbrand',
            unique_together={('user', 'brand')},
        ),
    ]
