# Generated by Django 6.0.5 on 2026-05-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_permission_unique_module_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='earned_amount',
        ),
        migrations.AlterField(
            model_name='broker',
            name='arc_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
