# Generated by Django 6.0.5 on 2026-05-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_role_description_status'),
        ('app', '0005_remove_client_earned_amount_alter_broker_arc_id'),
    ]

    operations = [
    ]
