# Generated by Django 6.0.5 on 2026-05-15 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20260515_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='rm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_brokers', to='app.user'),
        ),
    ]
