# Generated by Django 6.0.5 on 2026-05-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_role_brand_user_multi_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'brand')},
        ),
    ]
