# Generated by Django 6.0.5 on 2026-05-20 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_client_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('module', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('entity_label', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='app.user')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
