# Generated by Django 6.0.5 on 2026-05-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auditlog'),
        ('app', '0015_brand_code'),
    ]

    operations = [
    ]
